name: Weekly Test

on:
  schedule:
    - cron: '0 0 * * 0' # Run every Sunday at midnight UTC

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK (if applicable)
        uses: actions/setup-java@v2 # Change to your language/setup action if necessary
        with:
          java-version: '17'

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run Tests
        run: ./gradlew test