name: weekly_test

on:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: Build with Gradle
        run: ./gradlew build

      - name: List Test Classes
        id: list_tests
        run: |
          echo ::set-output name=test_classes::$(find ./src/test/java -name '*Test.java' | sed -e 's/^\.\///' -e 's/\//./g' -e 's/.java//')

      - name: Run Specific Tests
        run: ./gradlew test --tests "${{ steps.list_tests.outputs.test_classes }}"
