name: Java algo tests

on:
  schedule:
    - cron: '0 0 * * 0'  # Schedule to run every Sunday at midnight UTC
  workflow_dispatch: {}   # Enable manual workflow dispatch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'  # Set the desired Java version
          distribution: 'adopt'  # Specify the distribution here

      - name: Cache Gradle dependencies
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/*.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Build and Run Tests
        run: |
          # Print the current directory to debug path issues
          pwd

          # Navigate to your Java source directory
          cd /mnt/c/Users/ygult/waw-duck/funky-algorithm/java/src

          # List the files in the current directory to debug path issues
          ls -la

          # Ensure the gradlew script is executable
          chmod +x ./gradlew

          # Run Gradle tests for your Java project
          ./gradlew test --tests "org.example.test.*"
